### ISSUE TITLE
Attending? Say hi and I will add you as a contributor to this repo

### ISSUE THREAD

**Issue by elisabethirgens** [elisabethirgens/booster2024-git-workshop#1]
## Joining this workshop with me at Booster?

[Choose your own command line Git adventure](https://2024.boosterconf.no/program/thursday/1_short_talks_and_workshops/dreggen_3/choose-your-own-command-line-git-adventure/)
Thursday 14th March 2024
09:00 — lunch
Dreggen 3

Yay! And also: 

If you want to contribute to this repo, then say hi below and I will add you as a contributor
Or if you prefer to practice in a local repo on your laptop _without_ pushing any commits to this public remote repo, than that is of course perfectly fine

**Comment by maritane** [comment]
Hi!

**Comment by SindreFonnes** [comment]
hi

**Comment by tmavro** [comment]
Hi!

**Comment by 0Merlin0** [comment]
Hi

**Comment by krnome** [comment]
Hi!

**Comment by SaerdnaJ** [comment]
Hi

**Comment by Severinzz** [comment]
Hi

**Comment by mesutdurukal** [comment]
Hi

**Comment by rlu010** [comment]
hi

**Comment by MinaJoh96** [comment]
Hallaisikken

**Comment by cosimodpersia** [comment]
HI!

**Comment by oeheggel2** [comment]
hi

**Comment by sirtorbis** [comment]
Hi

**Comment by sGrevling** [comment]
Hi!

**Comment by sigurdc** [comment]
Hi

**Comment by ezagroba** [comment]
Hello, I feel left out, add me too!

**Comment by ankit-tiwari-tietoevry** [comment]
Hi

**Comment by tigergus** [comment]
Hei

**Comment by anneli** [comment]
👋

**Comment by janhak23** [comment]
hei

**Comment by tagelokoy** [comment]
Hei!

**Comment by elineh** [comment]
Hi

**Comment by skulstadv** [comment]
Hi

**Comment by tv2-hboge** [comment]
hei
